journal/urls.py
from django.urls import path
from .views import journal_detail_view

urlpatterns = [
    path('<int:id>', journal_detail_view)
]

journal_book/urls.py
from django.contrib import admin
from django.urls import include, path
from journal.views import add_journal_view, home_page_view

from django.conf import settings
from django.views.static import serve
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_page_view, name="home"),
    path('add-journal/', add_journal_view, name="add-journal"),
    path('user/', include('user.urls')),
    path('journal/', include('journal.urls')),
    url(r'^media/(?P<path>.*)$', serve,
        {'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,
        {'document_root': settings.STATIC_ROOT}),
]

user/urls.py
from django.urls import path
from .views import login_view, logout_view, signup_view

app_name = 'user'

urlpatterns = [
    path('signup/', signup_view, name="signup"),
    path('login/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
]

journal/models.py
from django.db import models
from django.contrib.auth.models import User


class Journal(models.Model):
    title = models.CharField(max_length=50)
    journal_content = models.TextField()
    key_moments = models.TextField(blank=True)
    date_created = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return f"{self.title} - {self.date_created}"

user/models.py
from django.db import models

journal/forms.py
from django import forms
from .models import Journal


class AddJournalForm(forms.ModelForm):
    class Meta:
        model = Journal
        fields = [
            'title',
            'journal_content',
            'key_moments',
        ]
        labels = {
            'title': ('Title'),
            'journal_content': ('Body'),
            'key_moments': ('Special Moments'),
        }
        widgets = {
            'key_moments': forms.Textarea(attrs={'placeholder': "Seperate each moment with ','"})
        }

journal/views.py
from django.contrib.auth import login
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from .forms import AddJournalForm
from .models import Journal


@login_required(login_url='user:login')
def home_page_view(request):
    context = {}

    journalList = Journal.objects.filter(author=request.user)
    if journalList:
        context.update({"journalList": journalList})

        for journal in journalList:
            if journal.key_moments:
                context.update({"keyMoments": journal.key_moments.split(',')})

    return render(request, 'home.html', context)


@login_required(login_url='user:login')
def add_journal_view(request):
    context = {}

    if request.method == 'POST':
        form = AddJournalForm(request.POST)

        if form.is_valid():
            data = form.cleaned_data
            titleError = validateTitle(data['title'])
            context.update({"titleError": titleError})
            if not titleError:
                formData = form.save(commit=False)
                formData.author = request.user
                formData.save()
                form = AddJournalForm()
                return redirect("home")

    else:
        form = AddJournalForm()

    context.update({"form": form})

    return render(request, 'add-journal.html', context)


def validateTitle(title):
    titleExists = Journal.objects.filter(title=title).exists()
    if titleExists:
        return "Title already exists!"


def journal_detail_view(request, id):
    data = Journal.objects.get(id=id)

    keyMoments = data.key_moments.split(',')
    context = {
        "data": data,
        "keyMoments": keyMoments,
    }
    return render(request, 'journal_detail.html', context)

user/views.py
from django.contrib.auth import login, logout
from django.http.response import HttpResponse
from django.shortcuts import redirect, render
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm


def signup_view(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect("user:login")
    else:
        form = UserCreationForm()

    return render(request, 'signup.html', {"form": form})


def login_view(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)

        if form.is_valid():
            login(request, form.get_user())
            return redirect("home")

    else:
        form = AuthenticationForm()

    return render(request, 'login.html', {"form": form})


def logout_view(request):
    if request.method == "POST":
        logout(request)
        return redirect('user:login')

journal/templates/add-journal.html
{% extends 'base.html' %}
{% block content%}


<form method="POST">
    {% csrf_token %}
    {% if titleError %}
    <span class="error">{{ titleError }}</span>
    {% endif %}
    {{ form.as_p }}
    <button type="submit" class="journal-submit-btn">Save</button>
</form>

{% endblock %}

journal/templates/base.html
{% load static %}

<html lang="en">

<head>
  <meta charset="UTF-8" />
  <title>Journal Book</title>
  <link rel="stylesheet" href="{% static 'styles.css' %}" />
</head>

<body>
  <div class="container">
    <nav class="navbar">
      <ul>
        <li>
          <a href="{% url 'home' %}">Journal Book</a>
        </li>
        {% if user.is_authenticated %}

        <li>Logged in as
          <span class="logged-user">{{ user.username }}</span>
        </li>

        {% endif %}

        <li>
          {% if request.path != '/user/signup/' %}
          <a href="/user/signup">
            <button class="signup-btn">Sign up</button>
          </a>
          {% endif %}

          {% if user.is_authenticated %}
          <form method="POST" action="{% url 'user:logout' %}">
            {% csrf_token %}
            <button type="submit" class="logout-btn">Logout</button>
          </form>
          {% elif request.path != '/user/login/' %}
          <a href="/user/login">
            <button class="signup-btn">Log in</button>
          </a>
          {% endif %}
        </li>
      </ul>
    </nav>
    {% block content %}

    {% endblock %}
  </div>
</body>

<script src="{% static 'script.js' %}">
</script>

</html>

journal/templates/home.html
{% extends 'base.html' %}
{% block content%}


{% if journalList %}
<h1 align="center">My Journals</h1>
<div class="journal-list">

    {% for journal in journalList %}

    <a class="journal" href="journal/{{ journal.id }}">
        <h2 class="journal-title" align="center">{{ journal.title }}</h2>
        <p class="journal-content">{{ journal.journal_content }}</p>

        {% if journal.key_moments %}

        <h4 class="journal-title">Special Moments:</h4>
        <ol>
            {% for moment in keyMoments %}

            <li>{{ moment }}</li>

            {% endfor %}
        </ol>

        {% endif %}

    </a>
    {% endfor %}

    {% else %}

    <h1 class="no-journals">No Journal created</h1>

    {% endif %}
</div>
<footer>
    <a href="{% url 'add-journal'%}" class="add-journal-btn">Add New Journal</a>
</footer>

{% endblock %}

journal/templates/journal_detail.html
{% extends 'base.html' %}
{% block content%}



<div class="journal-detail-content">
    <h4 class="journal-title">Date created: <span>{{ data.date_created }}</span></h4>
    <h2 align="center">{{ data.title }}</h2>
    <p>{{ data.journal_content }}</p>

    {% if data.key_moments %}

    <h4 class="journal-title">Special Moments:</h4>
    <ol>
        {% for moment in keyMoments %}

        <li>{{ moment }}</li>

        {% endfor %}
    </ol>

    {% endif %}

</div>

{% endblock %}

user/templates/login.html
{% extends 'base.html' %}

{% block content %}

<div class="login-form">
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="login-form-footer">
            <button type="submit">Login</button>
        </div>
    </form>
</div>

{% endblock%}

user/templates/signup.html
{% extends 'base.html' %}

{% block content %}

<div class="form">
    <form method="POST" class="signup-form">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="signup-submit-btn">Signup</button>
    </form>
</div>

{% endblock%}